_prefs: 
  mapid: scarndp.698e2446
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -71.016
  - 42.3514
  - 12
description: ''
format: png24
interactivity_layer: usAirports
layers: null
maxzoom: 16
minzoom: 4
name: No Fly Zones
source: "mapbox:///scarndp.65ae43e9,scarndp.0359fc40,scarndp.a69ec4e3,scarndp.170d2f35,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
template: ''
